FROM golang:1.18-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o application-server cmd/application-server/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/application-server /app/application-server
COPY configs /app/configs

EXPOSE 8081/udp

CMD ["/app/application-server"]