FROM golang:1.18-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o mediatory-server cmd/mediatory-server/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/mediatory-server /app/mediatory-server
COPY configs /app/configs

EXPOSE 8080

CMD ["/app/mediatory-server"]