# configs/config.yaml
servers:
  mediatory:
    port: 8080
    host: "0.0.0.0"
    log_level: "info"
  application:
    port: 9000
    host: "0.0.0.0"
    log_level: "info"
  tcp:
    host: "0.0.0.0"
    port: 5555
    connection_timeout: 300
    max_connections: 1000
    buffer_size: 4096
stun:
  server: "stun.l.google.com:19302"
  timeout_seconds: 5
  retry_count: 3
connection:
  hole_punch_attempts: 5
  hole_punch_timeout_ms: 500
  keep_alive_interval_seconds: 30